# Generated by Django 5.2.6 on 2025-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_fare',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='busroute',
            name='adult_fare',
            field=models.FloatField(default=500.0),
        ),
        migrations.AddField(
            model_name='busroute',
            name='bus_type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default='Non-AC', max_length=10),
        ),
        migrations.AddField(
            model_name='busroute',
            name='child_fare',
            field=models.FloatField(default=250.0),
        ),
    ]
