# Generated by Django 5.2.6 on 2025-09-30 06:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_booking_total_fare_busroute_adult_fare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='adult_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='child_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
