# Generated by Django 5.2.6 on 2025-09-30 09:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_alter_booking_adults_alter_booking_children_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.AlterModelOptions(
            name='busroute',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='busroute',
            name='adult_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='child_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='busroute',
            unique_together={('name', 'bus_type')},
        ),
    ]
